name: 'Build frontend'
description: 'Build frontend files for Umbraco V8'
inputs:
  frontend-directory:
    description: 'Path to the frontend directory'
    required: true
  cd-path:
    description: 'NPM cache dependency path'
    required: false
    deffault: '**/**.Frontend/npm-shrinkwrap.json'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path }}
    - name: NPM install
      run: npm install
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Install Gulp-cli
      run: npm install -g gulp-cli
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Install Gulp 
      run: npm install gulp
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Run gulp
      run: gulp releaseBuild
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
