name: 'Build frontend'
description: 'Build frontend files for Umbraco V9'
defaults:
  run:
    shell: powershell
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello 
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH