name: 'Build frontend'
description: 'Build frontend files for Umbraco V9'
inputs:
  cd-path:
    description: 'NPM cache dependency path'
    required: true
    default: '**/**.Frontend/package-lock.json'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path }}
    - name: NPM install
      run: npm install
      shell: powershell
    - name: Install Gulp 
      run: npm install -g gulp-cli
      shell: powershell
    - name: Run gulp
      run: gulp releaseBuild
      shell: powershell