name: 'Build frontend'
description: 'Build frontend files for Umbraco V8'
inputs:
  frontend-directory:
    description: 'Path to the frontend directory'
    required: true
  cd-path:
    description: 'NPM cache dependency path'
    required: true
    default: '**/**.Frontend/npm-shrinkwrap.json'
  app-path: 
    description: 'path to web application (usually the .web project)'
    required: true


# outputs:
  # hash:
    # description: "Hash of last frontend changes in GIT"
    # value: ${{ steps.FRONTEND_HASH.outputs.hash }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path == '' && '**/**.Frontend/npm-shrinkwrap.json' || inputs.cd-path }}
    
    - id: FRONTEND_HASH
      run: echo "::set-output name=hash::$(git log -1 --pretty=format:'%h' --follow '${{ inputs.frontend-directory }}')"       
      shell: powershell
      
    ### First make sure the directory assets exists, this is needed or cache action will throw an error
    - name: Create Directory.
      run: New-Item -Path "${{ inputs.app-path }}" -Name "assets" -ItemType "directory" -Force
      shell: powershell
    ### Check cache action for existing frontend build
    - name: Cache Frontend Build
      id: CACHE_FRONTEND
      uses: actions/cache@v3
      with:
        path: "${{ inputs.app-path }}\assets"
        key: frontend-cache-${{steps.FRONTEND_HASH.outputs.hash}}
        #key: frontend-cache-${{needs.Get-Frontend-Hash.outputs.hash}}
        
    ### below if will make sure this only runs when the frontend needs to be build    
    - name: NPM install
      if: steps.CACHE_FRONTEND.outputs.cache-hit != 'true'
      run: npm install
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Install Gulp-cli
      if: steps.CACHE_FRONTEND.outputs.cache-hit != 'true'
      run: npm install -g gulp-cli
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Install Gulp
      if: steps.CACHE_FRONTEND.outputs.cache-hit != 'true'
      run: npm install gulp
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
    - name: Run gulp
      if: steps.CACHE_FRONTEND.outputs.cache-hit != 'true'
      run: gulp releaseBuild
      working-directory: ${{ inputs.frontend-directory }}
      shell: powershell
        
        
    
