name: 'Build frontend'
description: 'Build frontend files for Umbraco V9'
inputs:
  frontend-dir:
    description: 'Path to the frontend directory'
    required: true
  cd-path:
    description: 'NPM cache dependency path'
    required: true
    default: '**/**.Frontend/package-lock.json'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path }}
    # - name: NPM install & Gulp ReleaseBuild
    #   run: |
    #         cd *Frontend
    #         npm install
    #         npm install gulp-cli
    #         gulp releaseBuild
      # shell: powershell
    - name: NPM install
      run: npm install
      working-directory: ${{ inputs.frontend-dir }}
      shell: powershell
    - name: Install Gulp 
      run: npm install gulp-cli
      working-directory: ${{ inputs.frontend-dir }}
      shell: powershell
    - name: Run gulp
      run: gulp releaseBuild
      working-directory: ${{ inputs.frontend-dir }}
      shell: powershell