name: 'Build frontend'
description: 'Build frontend files for Umbraco V10'
inputs:
  front-end-directory:
    description: 'Path to the frontend directory'
    required: true
  cd-path:
    description: 'NPM cache dependency path'
    required: true
    default: '**/**.Frontend/package-lock.json'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cd-path }}
    - name: NPM install
      run: npm install
      working-directory: ${{ inputs.front-end-directory }}
      shell: powershell
    - name: Install Gulp-cli
      run: npm install -g gulp-cli
      working-directory: ${{ inputs.front-end-directory }}
      shell: powershell
    - name: Install Gulp 
      run: npm install gulp
      working-directory: ${{ inputs.front-end-directory }}
      shell: powershell
    - name: Run gulp
      run: gulp releaseBuild
      working-directory: ${{ inputs.front-end-directory }}
      shell: powershell
